name: ğŸ“ Check Spelling

on:
  push:
    branches:
      - develop
      - master
  pull_request_target:
    branches:
      - develop
      - master
    types:
      - 'opened'
      - 'reopened'
      - 'synchronize'

jobs:
  spelling:
    name: ğŸ” Spelling Check
    permissions:
      contents: read
      pull-requests: read
      actions: read
    outputs:
      followup: ${{ steps.spelling.outputs.followup }}
    runs-on: ubuntu-24.04
    concurrency:
      group: spelling-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true

    steps:
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          show-progress: false
          submodules: recursive
          fetch-depth: 0

      - name: ğŸª„ Run Spelling Checker
        id: spelling
        uses: check-spelling/check-spelling@main
        with:
          checkout: true
          check_file_names: 1
          spell_check_this: check-spelling/spell-check-this@v0.0.24
          post_comment: 0
          warnings: bad-regex,deprecated-feature,noisy-file
          extra_dictionaries: |
            cspell:software-terms/src/softwareTerms.txt
            local:.github/actions/spell-check-this/dictionary.txt

  comment-pr:
    name: ğŸ’¬ Report (PR)
    runs-on: ubuntu-24.04
    needs: spelling
    permissions:
      pull-requests: write
    if: (success() || failure()) && needs.spelling.outputs.followup
    steps:
      - name: ğŸ’¬ Post Spelling Report
        uses: check-spelling/check-spelling@main
        with:
          checkout: true
          spell_check_this: check-spelling/spell-check-this@v0.0.24
          task: ${{ needs.spelling.outputs.followup }}
